### PR TITLE
monitor_utils.k8s: Prevent infinite looping when discovering k8s Custom Resources

### LINKED ISSUE #998: BUG: agent stuck in an infinite loop, while trying to discover K8S custom resources
We installed `scalyr-agent` on our k8s cluster through Helm, but it wasn't working as expected. While testing, we found a bug in Scalyr Agent that caused high CPU usage and logs not being sent. We suspect that it gets stuck in an endless loop while trying to perform k8s objects discovery. Specifically, it was stuck on our Redis pods. Agent was trying to discover its controllers, but was going into infinite loop when encountering unknown Redis k8s custom resource. Following lines were repeatedly appearing in debug logs (`/var/log/scalyr-agent-2/agent_debug.log` file):
```
2022-09-21 10:46:08.569Z Level 7 [core] [scalyr_agent.monitor_utils.k8s:775] cache value for Redis default/redis: <scalyr_agent.monitor_utils.k8s.Controller object at 0x7fa2e1e1f7f0> (allow_expired=True)
2022-09-21 10:46:08.569Z Level 7 [core] [scalyr_agent.monitor_utils.k8s:770] cache hit for Redis default/redis (allow_expired=True)
```
Notably, it works fine on k8s nodes where Redis pods are not running.
Default Agent configuration was used as provided by Helm chart.

Versions:
scalyr-agent - `2.1.33`
helm chart - `0.2.19`

### PR DESCRIPTION
**Pull request by xdvpser**
Resolves #998

### CODE REVIEW

**Comment by Kami** [comment]
@xdvpser Thanks for the contribution.

Did you eventually manage to confirm that the bug indeed lies in that piece of code or that's just one of the suspects?

**Comment by xdvpser** [comment]
> Did you eventually manage to confirm that the bug indeed lies in that piece of code or that's just one of the suspects?

@Kami Hi! Yes, after applying changes in this PR, building and deploying to our servers, it started working properly.

**Comment by Kami** [comment]
@xdvpser Thanks for confirming. I added basic mock based unit tests in #1004.

**Comment by Kami** [comment]
Merged into master via #1004 - thanks!

New dev build of Docker image with those changes should be available shortly (after CI finishes).

**Pull request closed without merging**
