### PR TITLE
Upgrade frozen binaries + Docker images to Python 3.11.3, upgrade AIO to Python 3.11.3

### PR DESCRIPTION
**Pull request by Kami**
This pull request upgrades frozen binaries packages from Python 3.11.0 to 3.11.2.

It also upgrades Docker Images from Python 3.8 to 3.11.2. This was already attempted in the past, but it didn't work since not all of the dependencies we use had 3.11 compatible wheels yet. Hopefully this has been resolved now.

### CODE REVIEW

**Comment by Kami** [comment]
Looks like ``TARGETVARIANT`` check in Dockerfile is broken / not working. No idea when this happened, but I will try to fix it (or use a different approach such as ``TARGETARCH`` value).

**Comment by Kami** [comment]
Looks like 3.11 musl wheel is not available yet, so I will need to wait a while longer - https://github.com/ijl/orjson/pull/327

**Comment by tomaz-s1** [comment]
orjson now ships 3.11 compatible musl wheels so hopefully this build should now pass and we can review and merge the pr - https://github.com/ijl/orjson/commit/c2514ab9ecdb9d42945f3fc6e18475b88bef8ec2

**Comment by tomaz-s1** [comment]
It looks like Alpine / musl build is now indeed passing - https://github.com/scalyr/scalyr-agent-2/actions/runs/4665395633/jobs/8258718537?pr=1075 🎉

**Pull request closed without merging**
