### PR TITLE
Circle CI and tox.ini updates

### PR DESCRIPTION
**Pull request by Kami**
This pull request includes the following changes:

1. Fix ``coverage`` tox target to make sure we run all the unit tests.

2. Update unit-test and coverage tox targets to generate junit XML report files. Those reports files are then used by Circle CI to provider a nicer visualization on test results, including test timing.

3. If there is a Circle CI job failure on master run, we will now get notified on Slack.

4. Pushing to a special ``automated_tests/`` prefixed branch will trigger builds for all the jobs (including the ones which only run on master). This will be used by our automated final sanity test which will be triggered by a Github PR / issue comment.

### CODE REVIEW

**Comment by Kami** [comment]
Here is an example of improved test result reporting on failure.

https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2/2516/workflows/e4ebe7c5-eda6-4af6-b07b-014f9c8e2450/jobs/32955/tests

Screenshot from 2020-04-16 18-25-27

https://circleci.com/build-insights/gh/scalyr/scalyr-agent-2/circle_ci_updates

Screenshot from 2020-04-16 18-26-22

**Comment by scalyr-cloud-tech-automations** [comment]
Triggered a new full Circle CI build using temporary testing branch named ``automated_tests/circle_ci_updates/26422`` (based on ``circle_ci_updates`` branch) :hourglass_flowing_sand:.

Result will be available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/26422.

Once the build has finished, new comment with the overall build status will be added, git commit status for this PR will be updated and temporary branch will be deleted.

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Comment by scalyr-cloud-tech-automations** [comment]
Circle CI pipeline for temporary branch ``automated_tests/circle_ci_updates/26422`` has finished with the status of ``failure`` .

Please investigate the failure, make any code changes and fixes (if necessary) and re-run the build via PR comment once regular PR build succeeds.

Build details are available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/26422

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Comment by scalyr-cloud-tech-automations** [comment]
Triggered a new full Circle CI build using temporary testing branch named ``automated_tests/circle_ci_updates/5706`` (based on ``circle_ci_updates`` branch) :hourglass_flowing_sand:.

Result will be available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/5706.

Once the build has finished, new comment with the overall build status will be added, git commit status for this PR will be updated and temporary branch will be deleted.

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Comment by scalyr-cloud-tech-automations** [comment]
Circle CI pipeline for temporary branch ``automated_tests/circle_ci_updates/5706`` has finished with the status of ``failure`` .

Please investigate the failure, make any code changes and fixes (if necessary) and re-run the build via PR comment once regular PR build succeeds.

Build details are available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/5706

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Comment by scalyr-cloud-tech-automations** [comment]
Triggered a new full Circle CI build using temporary testing branch named ``automated_tests/circle_ci_updates/11827`` (based on ``circle_ci_updates`` branch) :hourglass_flowing_sand:.

Result will be available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/11827.

Once the build has finished, new comment with the overall build status will be added, git commit status for this PR will be updated and temporary branch will be deleted.

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Comment by scalyr-cloud-tech-automations** [comment]
Circle CI pipeline for temporary branch ``automated_tests/circle_ci_updates/11827`` has finished with the status of ``success`` :tada:.

If the PR has been approved and is fully update to date / in sync with master, feel free to merge it into master.

Build details are available at https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2?branch=automated_tests/circle_ci_updates/11827

---
This is an automated message sent by the Scalyr StackStorm build automations bot.

**Pull request merged**
