### PR TITLE
Upgrade Python 3.8 used by Docker images from 3.8.10 to 3.8.12

### PR DESCRIPTION
**Pull request by Kami**
This pull request updates Python used by Docker images from 3.8.10 to 3.8.12.

Latest version contains some small bug and security fixes - https://docs.python.org/3.8/whatsnew/changelog.html#changelog.

I also wanted to update version used by the Windows installer, but installer binaries for 3.8.12 are not available - apparently that's normal for the release schedule (https://www.python.org/downloads/release/python-3812/).

> Finally, while we're not providing binary installers anymore, for those users who produce installers, we upgraded the OpenSSL version used to 1.1.1l. Take a look at the change log for details.

### CODE REVIEW

**Comment by Kami** [comment]
@ArthurKamalov it looks like Docker image tests are failing - not sure if there is a bug with image caching or similar.

**Comment by Kami** [comment]
Ugh, it does look like the base image has changed from Buster to Bullseye:

```bash
kami ~/w/scalyr/scalyr-agent-2/.github (git:docker_images_upgrade_python)$ docker run -it python:3.8.10 /bin/bash
Unable to find image 'python:3.8.10' locally
3.8.10: Pulling from library/python
0bc3020d05f1: Pull complete 
a110e5871660: Pull complete 
83d3c0fa203a: Pull complete 
a8fd09c11b02: Pull complete 
14feb89c4a52: Pull complete 
70752631d778: Pull complete 
a528eeaeed26: Pull complete 
01a2d9ea11b3: Pull complete 
55af698de0cb: Pull complete 
Digest: sha256:f7981c32c931f07d053f6867d7882169a9769528619e8dc475bf9b5cbec51679
Status: Downloaded newer image for python:3.8.10
root@bf6b4d44fec3:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@bf6b4d44fec3:/# exit
kami ~/w/scalyr/scalyr-agent-2/.github (git:docker_images_upgrade_python)$ docker run -it python:3.8.12 /bin/bash
Unable to find image 'python:3.8.12' locally
3.8.12: Pulling from library/python
Digest: sha256:4c4e6735f46e7727965d1523015874ab08f71377b3536b8789ee5742fc737059
Status: Downloaded newer image for python:3.8.12
root@b31e06e825d9:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@b31e06e825d9:/# 
```

@ArthurKamalov How do you think we should proceed here? It looks like Buster will be EOL later this year so maybe switch to Bullseye is fine.

**Comment by ArthurKamalov** [comment]
> @ArthurKamalov I noticed there is still `Dockerfile` in the repo root? Is this file still used / needed by anything?

Yes, that was left unnoticed, sorry. Deleted.

**Comment by Kami** [comment]
@ArthurKamalov Thanks.

Technically as you said, that change should be transparent to the end user (distro version), but I still added changelog entry to be on the safe side :)

**Comment by ArthurKamalov** [comment]
Just for the record. Renamed from `buster` naming to `debian` everywhere in image build logic.

**Review by ArthurKamalov — APPROVED** [review]

**Pull request merged**
