### PR TITLE
Add support for new tracemalloc memory profiler (Python >= 3.5)

### PR DESCRIPTION
**Pull request by Kami**
This pull request adds support for new memory profiler which uses native Python >= 3.4 functionality from the tracemalloc module (https://docs.python.org/3/library/tracemalloc.html).

Used can select this profiler by setting ``memory_profiler`` config option.

I also added new ``memory_profiler_max_lines`` config option which tells memory profiler how many lines for the top largest items to include in the profiling file (defaults to 100 - up from previous default of 50).

And there are also 2 other tracemalloc related config options - ``memory_profiler_max_frames``, ``memory_profiler_include_traceback``.

## Background, Context

We already have ``pympler`` based memory profiler, but that profiler is more limited and provides less context than tracemalloc which is available in stdlib from Python 3.4 onwards.

In the past, Docker images used Python 2.7 so we couldn't use it (this functionality is Python >= 3.4 only), but now Docker  Images use Python 3 so we can use it.

Thanks to @dlobue  for bringing this up.

### pympler (existing profiler)

```
timestamp: 1660909021, total lines: 32 (aggregated values)
                       types |   # objects |   total size
============================ | =========== | ============
                         str |       45530 |      6.52 MB
                        dict |        8377 |      3.34 MB
                        code |       10110 |      1.39 MB
                        type |        1518 |      1.34 MB
                        list |        8867 |      1.25 MB
                       tuple |        7571 |    486.88 KB
                         set |         945 |    447.22 KB
          _io.BufferedWriter |           7 |    277.20 KB
                     weakref |        2338 |    182.66 KB
          wrapper_descriptor |        2147 |    167.73 KB
          _io.BufferedReader |           4 |    140.69 KB
                         int |        4388 |    129.75 KB
                 abc.ABCMeta |         106 |    106.14 KB
  builtin_function_or_method |        1476 |    103.78 KB
           getset_descriptor |        1444 |    101.53 KB
           method_descriptor |        1378 |     96.89 KB
         function (__init__) |         662 |     87.92 KB
                   frozenset |         130 |     62.94 KB
          typing.GenericMeta |          71 |     62.06 KB
                    property |         783 |     61.17 KB
            _sre.SRE_Pattern |         120 |     52.98 KB
          function (_remove) |         385 |     51.13 KB
           member_descriptor |         545 |     38.32 KB
                        cell |         742 |     34.78 KB
       _ctypes.PyCSimpleType |          29 |     29.27 KB
                 _io.BytesIO |           3 |     28.10 KB
         function (__repr__) |         202 |     26.83 KB
                 numpy.ufunc |         109 |     25.55 KB
               enum.EnumMeta |          24 |     24.42 KB
           collections.deque |          39 |     24.07 KB

timestamp: 1660909021, total lines: 17 (diff since the last capture)
                                                       types |   # objects |   total size
============================================================ | =========== | ============
                                                         str |          45 |      4.59 KB
                                                        list |           7 |   1016     B
                                                 _io.BytesIO |           1 |    749     B
                                                       tuple |           9 |    584     B
                                                         int |          17 |    484     B
                                                        cell |           3 |    144     B
                                                       float |           6 |    144     B
                                 function (receive_response) |           1 |    136     B
                                                        dict |           0 |     64     B
                                     http.client.HTTPMessage |           1 |     56     B
  scalyr_agent.log_processing.LogFileIterator.MarkGeneration |           1 |     56     B
                                    http.client.HTTPResponse |           1 |     56     B
     scalyr_agent.log_processing.LogFileIterator.BufferEntry |           1 |     56     B
                                                _thread.lock |          -1 |    -40     B
                                  builtin_function_or_method |          -1 |    -72     B
```

### tracemalloc

1. Without complete traceback (less verbose and less context):

```
timestamp: 1660915174, total lines: 30 (aggregated values)
#1: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:3547: 14.8 KiB, 131 count
	"SCALYR_%s" % param_name.upper()
#2: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:73: 7.5 KiB, 62 count
	for key, value in six.iteritems(key_values):
#3: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:98: 7.4 KiB, 7 count
	self.__map[key] = value
#4: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:142: 5.9 KiB, 94 count
	return list(self.__map.items())
#5: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/parser.py:126: 5.2 KiB, 80 count
	return "".join(my_slice)
#6: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py:1468: 5.1 KiB, 2 count
	self.__buffer.write(content)
#7: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:161: 4.5 KiB, 8 count
	result.__map = self.__map.copy()
#8: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:69: 4.0 KiB, 65 count
	self.__map = {}
#9: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:1217: 3.0 KiB, 34 count
	self._run_state = RunState(fake_clock=fake_clock)
#10: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:949: 2.7 KiB, 35 count
	self.__map = {}
...

timestamp: 1660915174, total lines: 30 (diff since the last capture)
#1: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_client.py:601: 2.4 KiB (+832 bytes), 3 count (+1)
	return self.__receive_response(body_str, current_time)
#2: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:73: 7.5 KiB (+240 bytes), 62 count (+2)
	for key, value in six.iteritems(key_values):
#3: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:546: 2.2 KiB (+192 bytes), 34 count (+3)
	original_path = list(sys.path)
#4: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py:423: 0.7 KiB (+168 bytes), 5 count (+1)
	self.__workers = dict()  # type: Dict[six.text_type, CopyingManagerWorker]
#5: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:150: 0.8 KiB (+128 bytes), 12 count (+2)
	return list(self.__map.keys())
#6: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:489: 0.4 KiB (-128 bytes), 6 count (-2)
	workers = list(self.__config.get_json_array("workers"))
#7: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:122: 2.4 KiB (+72 bytes), 23 count (+1)
	return six.iterkeys(self.__map)
#8: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:4706: 0.7 KiB (+72 bytes), 10 count (+1)
	result = dict()
#9: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:142: 5.9 KiB (+64 bytes), 94 count (+1)
	return list(self.__map.items())
#10: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:3547: 14.8 KiB (0 bytes), 131 count (0)
	"SCALYR_%s" % param_name.upper()
#11: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:98: 7.4 KiB (0 bytes), 7 count (0)
	self.__map[key] = value
#12: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/parser.py:126: 5.2 KiB (0 bytes), 80 count (0)
	return "".join(my_slice)
#13: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py:1468: 5.1 KiB (0 bytes), 2 count (0)
	self.__buffer.write(content)
#14: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:161: 4.5 KiB (0 bytes), 8 count (0)
	result.__map = self.__map.copy()
#15: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:69: 4.0 KiB (0 bytes), 65 count (0)
	self.__map = {}
#16: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:1217: 3.0 KiB (0 bytes), 34 count (0)
	self._run_state = RunState(fake_clock=fake_clock)
#17: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:949: 2.7 KiB (0 bytes), 35 count (0)
	self.__map = {}
#18: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:951: 2.4 KiB (0 bytes), 22 count (0)
	self._environment_aware_map = {}
#19: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:575: 1.9 KiB (0 bytes), 42 count (0)
	self._items = []
#20: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:843: 1.8 KiB (0 bytes), 29 count (0)
	self.__condition = threading.Condition()
...
```

3. With complete traceback (more context):

```
timestamp: 1660915174, total lines: 30 (aggregated values)
#1: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:3547: 14.8 KiB, 131 count
	"SCALYR_%s" % param_name.upper()

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py", line 3349
	    self.__lock = threading.Lock()
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 720
	    result.append(LogMatcher(configuration, log_config))
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 428
	    self.__config, self.__monitors
	  File "scalyr_agent/agent_main.py", line 496
	    copying_manager = CopyingManager(config, monitors_manager.monitors)
	  File "scalyr_agent/agent_main.py", line 1268
	    disable_cache_config=disable_cache_config,
#2: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:73: 7.5 KiB, 62 count
	for key, value in six.iteritems(key_values):

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py", line 1468
	    self.__buffer.write(content)
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py", line 1402
	    self.__append_page_to_buffer(self.__page_size - self.__buffer.tell())
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py", line 657
	    self.__fill_buffer(current_time)
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py", line 2541
	    current_time=current_time
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/worker.py", line 955
	    (callback, buffer_filled) = processor.perform_processing(add_events_request)
#3: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:98: 7.4 KiB, 7 count
	self.__map[key] = value

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 98
	    self.__map[key] = value
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 118
	    self[key] = value
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 4165
	    config_object.put(field, default_value)
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 2790
	    env_aware=True,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 198
	    self.__config, self.__file_path
#4: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:142: 5.9 KiB, 94 count
	return list(self.__map.items())

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 3547
	    "SCALYR_%s" % param_name.upper()
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 4409
	    deprecated_names=deprecated_names,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 2883
	    env_aware=True,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 198
	    self.__config, self.__file_path
	  File "scalyr_agent/agent_main.py", line 484
	    config.parse()
#5: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/parser.py:126: 5.2 KiB, 80 count
	return "".join(my_slice)

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 142
	    return list(self.__map.items())
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/third_party/six.py", line 589
	    return iter(d.items(**kw))
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 4759
	    for (key, value) in six.iteritems(object_value):
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 4680
	    object_value=source_config, substitutions=substitutions
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py", line 187
	    self.__perform_substitutions(self.__config)
#6: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py:1468: 5.1 KiB, 2 count
	self.__buffer.write(content)

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_client.py", line 601
	    return self.__receive_response(body_str, current_time)
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/worker.py", line 588
	    (result, bytes_sent, full_response) = get_response()
	  File "/Users/tomaz/.pyenv/versions/3.6.13/lib/python3.6/threading.py", line 916
	    self.run()
	  File "/Users/tomaz/.pyenv/versions/3.6.13/lib/python3.6/threading.py", line 884
	    self._bootstrap_inner()
#7: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:161: 4.5 KiB, 8 count
	result.__map = self.__map.copy()

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 161
	    result.__map = self.__map.copy()
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 708
	    % monitor.module_name,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 428
	    self.__config, self.__monitors
	  File "scalyr_agent/agent_main.py", line 496
	    copying_manager = CopyingManager(config, monitors_manager.monitors)
	  File "scalyr_agent/agent_main.py", line 1268
	    disable_cache_config=disable_cache_config,
#8: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:69: 4.0 KiB, 65 count
	self.__map = {}

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 161
	    result.__map = self.__map.copy()
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 700
	    configs.append(entry.copy())
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 428
	    self.__config, self.__monitors
	  File "scalyr_agent/agent_main.py", line 496
	    copying_manager = CopyingManager(config, monitors_manager.monitors)
	  File "scalyr_agent/agent_main.py", line 1268
	    disable_cache_config=disable_cache_config,
#9: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:1217: 3.0 KiB, 34 count
	self._run_state = RunState(fake_clock=fake_clock)

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py", line 546
	    original_path = list(sys.path)
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/monitors_manager.py", line 495
	    return load_monitor_class(monitor_module, os.pathsep.join(paths_to_pass))[0]
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/monitors_manager.py", line 527
	    module_name, additional_python_paths
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/monitors_manager.py", line 353
	    configuration,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/monitors_manager.py", line 76
	    configuration, platform_controller
#10: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:949: 2.7 KiB, 35 count
	self.__map = {}

Traceback:

  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 73
	    for key, value in six.iteritems(key_values):
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py", line 160
	    result = JsonObject()
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 708
	    % monitor.module_name,
	  File "/Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py", line 428
	    self.__config, self.__monitors
	  File "scalyr_agent/agent_main.py", line 496
	    copying_manager = CopyingManager(config, monitors_manager.monitors)
...

timestamp: 1660915174, total lines: 30 (diff since the last capture)
#1: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_client.py:601: 2.4 KiB (+832 bytes), 3 count (+1)
	return self.__receive_response(body_str, current_time)
#2: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:73: 7.5 KiB (+240 bytes), 62 count (+2)
	for key, value in six.iteritems(key_values):
#3: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:546: 2.2 KiB (+192 bytes), 34 count (+3)
	original_path = list(sys.path)
#4: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/copying_manager/copying_manager.py:423: 0.7 KiB (+168 bytes), 5 count (+1)
	self.__workers = dict()  # type: Dict[six.text_type, CopyingManagerWorker]
#5: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:150: 0.8 KiB (+128 bytes), 12 count (+2)
	return list(self.__map.keys())
#6: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:489: 0.4 KiB (-128 bytes), 6 count (-2)
	workers = list(self.__config.get_json_array("workers"))
#7: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:122: 2.4 KiB (+72 bytes), 23 count (+1)
	return six.iterkeys(self.__map)
#8: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:4706: 0.7 KiB (+72 bytes), 10 count (+1)
	result = dict()
#9: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:142: 5.9 KiB (+64 bytes), 94 count (+1)
	return list(self.__map.items())
#10: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/configuration.py:3547: 14.8 KiB (0 bytes), 131 count (0)
	"SCALYR_%s" % param_name.upper()
#11: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:98: 7.4 KiB (0 bytes), 7 count (0)
	self.__map[key] = value
#12: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/parser.py:126: 5.2 KiB (0 bytes), 80 count (0)
	return "".join(my_slice)
#13: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/log_processing.py:1468: 5.1 KiB (0 bytes), 2 count (0)
	self.__buffer.write(content)
#14: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:161: 4.5 KiB (0 bytes), 8 count (0)
	result.__map = self.__map.copy()
#15: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:69: 4.0 KiB (0 bytes), 65 count (0)
	self.__map = {}
#16: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:1217: 3.0 KiB (0 bytes), 34 count (0)
	self._run_state = RunState(fake_clock=fake_clock)
#17: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:949: 2.7 KiB (0 bytes), 35 count (0)
	self.__map = {}
#18: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/scalyr_monitor.py:951: 2.4 KiB (0 bytes), 22 count (0)
	self._environment_aware_map = {}
#19: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/json_lib/objects.py:575: 1.9 KiB (0 bytes), 42 count (0)
	self._items = []
#20: /Users/tomaz/w/scalyr-agent-2/scalyr_agent/util.py:843: 1.8 KiB (0 bytes), 29 count (0)
	self.__condition = threading.Condition()
...
```

It's worth noting that it also includes code from stdlib, but that's because I'm using a virtualenv. I believe this issue shouldn't exist with deb/rpm packages and Docker images (I will verify it and make adjustments, if necessary).

## TODO

- [x] Tests

### CODE REVIEW

**Review by ArthurKamalov — APPROVED** [review]
LGTM so far.  Do you plan to do new benchmarking/measuring, or it just an upgrade? :slightly_smiling_face:

**Comment by Kami** [comment]
@ArthurKamalov 

> Do you plan to do new benchmarking/measuring, or it just an upgrade? 🙂

We plan to use this to troubleshoot some of the weird memory issues we are seeing in some very large k8s clusters.

**Comment by Kami** [comment]
I also pushed a small improvement which adds new ``enable_cpu_profiling`` and ``enable_memory_profiling`` config option - 392dfafb9e323495b564eb59f7c0d8ea253750bd.

With this config option, user can independently enable either CPU or memory profiling (or both). Existing ``enable_profiling`` config option only allows user to enable both at the same time.

As part of that change, I also noticed a small bug which I fixed - profiler would only be enabled if ``self.__log_warnings`` was true since the code was incorrectly nested under that if.

**Review by ArthurKamalov — APPROVED** [review]
LGTM

**Comment by Kami** [comment]
Pushed another change which also allow user to set custom trace filters for the tracemalloc profiler. This should make it easier to exclude the noise and only focus on specific code paths.

Example usage:

```javascript
...
memory_profiler_ignore_path_globs: ["**/scalyr_agent/configuration.py", "**/scalyr_agent/util.py", "**/scalyr_agent/json_lib/**"]
...
```

**Review by dlobue — APPROVED** [review]
LGTM

**Pull request merged**
