### PR TITLE
Add missing CA root certs from FedRAMP envs

### PR DESCRIPTION
**Pull request by epf**
We are not allowed to use Let's Encrypt in FedRAMP environments and we do not currently trust the most of the root CAs that are in use in our FedRAMP environments.

I have added the missing root CA certs in this PR.

### CODE REVIEW

**Comment by tomaz-s1** [comment]
@epf Thanks. 

Do we have some existing public endpoints where we can test the agent to confirm all those certs work correctly?

**Comment by anatolyp-s1** [comment]
@epf I see a couple tests failing - anything of concern?

**Comment by alesnovak-s1** [comment]
> @epf I see a couple tests failing - anything of concern?

The tests are not completely stable at the moment. I will first try to rerun them.

**Comment by alesnovak-s1** [comment]
> @epf I see a couple tests failing - anything of concern?

Everything seems fine now, you can ignore the coverage test failing.

**Review by alesnovak-s1 — APPROVED** [review]

**Pull request merged**
