### PR TITLE
Dummy change to test codecov PR comments

### PR DESCRIPTION
**Pull request by Kami**
Dummy change to see if codecov PR update comments are working.

See https://github.com/scalyr/scalyr-agent-2/pull/378#issuecomment-580253992 for details.

### CODE REVIEW

**Comment by Kami** [comment]
@ArthurKamalov something weird is going on with ``smoke-standalone-26-tls12`` Circle CI job.

It says that that job is queued yet the whole build has failed (or during the previous build, succeeded).

Any ideas?

**Comment by Kami** [comment]
Same issue during re-run - https://app.circleci.com/github/scalyr/scalyr-agent-2/pipelines/399a826a-6686-472f-aa90-3762ee274312/workflows/84545902-da82-437e-8462-315e1ba008e9

I wonder if it's related to number of containers we have or similar?

**Comment by ArthurKamalov** [comment]
@Kami, looks like it finished, no? Now I see that unittest-38 is pending, but it is only on github widget and it has a weird icon in jobs list on CircleCI.

**Comment by Kami** [comment]
@ArthurKamalov Yeah the problem is that the build and that Circle CI job actually finishes, but the Github Status check for that job isn't updated.

**Comment by czerwingithub** [comment]
@Kami @ArthurKamalov Huh... it looks like the problem is on CircleCI's side.  If you look closely at the CircleCI information, it is marked as "QUEUED" at the top even though it looks like it has finished.

**Pull request closed without merging**
