### PR TITLE
Make k8s_ignore_namespaces an ArrayOfStrings

### PR DESCRIPTION
**Pull request by echee2**
# Background

`k8s_ignore_namespaces` is inconsistently handled.  It should be typed as an `ArrayOfStrings`, which is comma-delimited.  This enables user to specify a single comma-separated string environment variable, consistent with some other parameters.

 However, to preserve legacy behavior (splittable by whitespace), I define a new type `SpaceAndCommaSeparatedArrayOfStrings` which is a subclass of `ArrayOfStrings`.  (And necessary plumbing to make it work).

# Changes

1. Make `k8s_ignore_namespaces` an SpaceAndCommaSeparatedArrayOfStrings.
2. Remove duplicate `k8s_ignore_namespaces` from `kubernetes_monitor.py`

# Testing
- Augmented `_test_environment_aware_global_params` to handle ArrayOfString types.
- manual testing: Entered the following configmap entry:
`SCALYR_K8S_IGNORE_NAMESPACES: "kube-system a , b , c"`
- verified agent.log shows correct ignored namespaces:
image

### CODE REVIEW

**Comment by echee2** [comment]
Yep, still working on accepting spaces. (Sorry, I should have noted this
after our standup yesterday)

**Comment by imron** [comment]
Ok.  Should I wait until those changes are made until finalizing the review?

I think in the meantime we can get back to the customer and specify the blacklist using spaces as the delimiter.

**Comment by echee2** [comment]
I believe @Wei-Li Liu <weili@scalyr.com> already notified customer to use
spaces.

Yes, please wait for fix before review.

**Comment by echee2** [comment]
@imron should be ready for review

**Comment by echee2** [comment]
@imron I've restored the local k8s_monitor's version of the config param but coded the global one to override.  This PR is ready for review.

**Comment by echee2** [comment]
@imron could you review this asap please.  I plan on making a new release and would like to include this fix. Thx.

**Pull request merged**
